### PR TITLE
Update GitHub workflow to publish to Maven Central

### PR DESCRIPTION
**Pull request by cketti**

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]
Looks good!

**Comment by JakeWharton** [comment]
Because the version is 0.2.0-SNAPSHOT you'll only push to the snapshot repo. You need to change it to 0.2.0 to stage a repository.

See our release steps for setups like this: https://github.com/cashapp/licensee/blob/trunk/RELEASING.md

**Comment by cketti** [comment]
The idea was to publish to the snapshot repository to test if I've set up the secrets correctly. I'll do a 0.2.0 release once I know this is working.

**Comment by JakeWharton** [comment]
Ah, okay cool. You can add automatic snapshot publishing to `main` builds by adding a similar config to `build.yaml`: https://github.com/cashapp/turbine/blob/f8cc82a407a7e9a789da94c6363402a2488f1332/.github/workflows/build.yaml#L27-L31

**Pull request merged**
