### PR TITLE
Build all possible targets

### PR DESCRIPTION
**Pull request by JakeWharton**
Previously only a single native target was built and it depended on the user's host machine OS (0.1 in Maven Central only supprots `linux64`). This enables all targets supported per https://kotlinlang.org/docs/multiplatform-dsl-reference.html#targets.

Unfortunately this requires deploying from two OSes: Mac OS and Linux.

 -  If you deploy from Mac OS every target is built except for `linuxMips32` and `linuxMipsel32`. These can be published to Sonatype as part of a separate call to

        ./gradlew \
            publishLinuxMips32PublicationToSonatypeRepository \
            publishLinuxMipsel32PublicationToSonatypeRepository`

    and then both repositories closed & released at once.

 -  If you deploy from Linux none of the Mac OS targets are built. They can be published to Sonatype as part of a separate call to

        ./gradlew \
            publishIosArm32PublicationToSonatypeRepository \
            publishIosArm64PublicationToSonatypeRepository \
            publishIosSimulatorArm64PublicationToSonatypeRepository \
            publishIosX64PublicationToSonatypeRepository \
            publishMacosArm64PublicationToSonatypeRepository \
            publishMacosX64PublicationToSonatypeRepository \
            publishTvosArm64PublicationToSonatypeRepository \
            publishTvosSimulatorArm64PublicationToSonatypeRepository \
            publishTvosX64PublicationToSonatypeRepository \
            publishWatchosArm32PublicationToSonatypeRepository \
            publishWatchosArm64PublicationToSonatypeRepository \
            publishWatchosDeviceArm64PublicationToSonatypeRepository \
            publishWatchosSimulatorArm64PublicationToSonatypeRepository \
            publishWatchosX64PublicationToSonatypeRepository \
            publishWatchosX86PublicationToSonatypeRepository

    and then both repositories closed & released at once.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Alternatively, we could drop Linux MIPS support (I've never seen them used) and that would allow all targets to be deployed from Mac / Mac CI worker.

I can't use the library without at least _some_ of these targets added. A safe subset is to match kotlinx.coroutines's [list](https://github.com/Kotlin/kotlinx.coroutines/blob/dea2ca5139ec20d1420c1a4561875c297bdeb613/gradle/compile-native-multiplatform.gradle#L16-L31). These can all be built from a Mac worker.

**Comment by cketti** [comment]
Thanks!

I guess a GitHub workflow to build the artifacts for all platforms is the easiest way to go. Any suggestion on where I can find a working config to copy?

**Comment by JakeWharton** [comment]
The ones in Turbine are pretty simple: https://github.com/cashapp/turbine/tree/trunk/.github/workflows

If you're going to include the Linux MIPS targets you'll need two jobs, one on Mac and one on Linux. We do this on a few projects, too. I'll have to find one when I get to a computer.

**Comment by JakeWharton** [comment]
I didn't even commit the MIPS targets 🤦 . I would say let's go without them for now unless someone comes complaining for them.

**Pull request merged**
